# Generated by Django 3.0.2 on 2020-01-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_code', models.IntegerField(null=True)),
                ('name', models.TextField()),
                ('contact_number', models.IntegerField(null=True)),
                ('address', models.TextField()),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('household_size', models.IntegerField(null=True)),
                ('household_income', models.IntegerField(null=True)),
                ('submission_date', models.DateTimeField()),
            ],
        ),
    ]
