# Generated by Django 3.0.2 on 2020-01-11 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beanie', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demographics',
            new_name='Demographic',
        ),
    ]
